#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "bad luck"
# for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Best School" for the other iteration

i=0
while (( i < 11 )); do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
    	echo "good luck"
    else
	echo "Best School"
    fi
        ((i++))
done
