#!/usr/bin/env bash

# This script displays the content of the current directory
# where only the part of the name after the first dash is displayed

for file in *; do
    # Check if the file is not hidden
    if [[ ! "$file" == .* ]]; then
        if [[ "$file" == *-* ]]; then
            name=$(echo "$file" | cut -d '-' -f 2-)
            echo "$name"
        else
            echo "$file"
        fi
    fi
done
